trigger:
- main

pool: default

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore dependencies'
  inputs:
    command: 'restore'
    projects: 'MrService.csproj'
    

- task: DotNetCoreCLI@2
  displayName: 'Build web project'
  inputs:
    version: '3.1.0'
    command: 'build'
    projects: 'MrService.csproj'